### ISSUE TITLE
CKEDITOR NOT WORKING (even if i click ckeditor not working? click here)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#125]
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?ckeditor1=
LOADS FOREVER STUCK
![snap 2018-03-02 at 18 57 13](https://user-images.githubusercontent.com/20817185/36913868-8c8366fe-1e4b-11e8-800b-2bf06645091c.png)

Are you even testing this? what would this button do?

**Comment by dnelband** [comment]
this link is not supposed to happend, now clicking on that button will bring a normal textarea. i need to change the editor because it behaves broken on firefox, though it works from cdn, but i have'nt caught this error after i changed to local, i should've clean the cache. in any case i need to find an editor which works on all browser from local, in the meanwhile this switch to textarea in firefox works

**Comment by dnelband** [comment]
i'll label it "ready" when i change the editor. but the issue that leads to that link is fixed

**Comment by dnelband** [comment]
i've switchted to another editor, it is quite basic but its ok for now, i will continue trying other libraries, but the problem is that due to the fact that its on zeronet there are a lot of restrictions to development or integrating 3rd party components due to the lack of server & restriction on cross-origins (because its in an iframe). but im looking for something better, or i'll have to expand the current one's functionality

**Comment by haschimoto** [comment]
Dont spend time on that...
A supersimple efitor is enough.
