### ISSUE TITLE
first comment ever on first page is "9 years ago"?

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#171]
loading page 25 at this moment in time shows this:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=main+sb=new+p=25
![snap 2018-06-29 at 18 54 27](https://user-images.githubusercontent.com/20817185/42104731-fe3062d6-7bcd-11e8-8fb7-4c7d7c1f4fec.png)

Let's examine the situation:
- What makes Zerovoat think this comment is 9 year sold?
- Any explanation how this was possible?

**Comment by dnelband** [comment]
this is the oldest post (that wasnt deleted) so i guess that the way the topic was saved in the users data.json was wrong, i remember that instead of  Date.now() which is the correct why to get the current time in js i accidently wrote new Date() or sth like that so that could explain why it shows 9 years ago. ive jury rigged anything older then the 2nd oldest post to have a max time ago of a year. is that ok ? the problem doesnt reproduce itself
