### ISSUE TITLE
the site behaves WEIRD and not functional

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#35]
every time i load/reload i get immediately PUBLISHED content, and NOTHING shown up:
![snap 2017-06-16 at 09 38 58](https://user-images.githubusercontent.com/20817185/27216862-bfe330c4-5277-11e7-98e9-8dedd81c0296.png)

**Comment by dnelband** [comment]
in order to switch to cdn i wanted to create a new cluster and copy all the data to it bulk, in order to avoid any duplications, but the problem is that now something goes wrong during sign & publish (in that new cluster) so almost no files are published. i switched it yesterday night so it wasn't like that for long.

i've switched it back to normal now, while im finding the problem with the new cluster. it works on zn.maly & bit.surf so if you update it should work localy.

sorry, it seemed to work yesterday night

**Comment by haschimoto** [comment]
site still doesnt show all the topics after rebuilding DB, and also loading FOREVER clicking on the topics visible, e.g.:
/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?view:topic+topic_id=1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp33
