### ISSUE TITLE
zv.anon: S&P doesnt update Cluster, so changes are local only

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#53]
added new zv.anon userid, then commented, cluster is updated on that machine:
![snap 2017-06-25 at 12 30 43](https://user-images.githubusercontent.com/20817185/27515388-51156fb8-59a2-11e7-8144-74e3a60ed3e9.png)

on other remote machines, the cluster is NOT updated, even when force-check updates:
![snap 2017-06-25 at 12 30 31](https://user-images.githubusercontent.com/20817185/27515392-6131ad76-59a2-11e7-9d9d-83d9d046a7d5.png)

**Comment by haschimoto** [comment]
maybe is that because the cluster DB is optional? or isnt the DB optional?

**Comment by haschimoto** [comment]
as soon as i use a ZEROID cert, the user is also shown to be registered, but the cluster is updated immediatley also on ALL REMOTE machines:
![snap 2017-06-25 at 12 37 41](https://user-images.githubusercontent.com/20817185/27515429-206c8fe4-59a3-11e7-839c-206a2164d570.png)

Hence the zv.anon user is NOT signed and published to other machines correctly as advertised like in case of a real zeroid.
So the user data folder of zv.anon is unkown for any other machines, as its not correctly signed&published, hence no comments or upvotes of that zv.anon user ever gets distributed.

**Comment by haschimoto** [comment]
interestingly, the #no of channels is always the same on all proxies or local machine:
![snap 2017-06-25 at 12 41 38](https://user-images.githubusercontent.com/20817185/27515451-b46de3aa-59a3-11e7-953b-4bbf27631b40.png)

It is 42 in above screenshot.

I guess adding any new zv.anonymous user doesnt add any channel?

**Comment by dnelband** [comment]
try now, if you dont get a new user generated, first delete the user from users.json & restart, but it should work regardless.

can now sign & publish content from proxies & local  with zv.anonymous

**Comment by haschimoto** [comment]
i cannot SP from local with zv.anon.
either the generated CERT ID is identicial to the ZEROID, then of course i can SP and it works.
But when i log out and it generates a new one, that one seems OLD (maybe tied to or a simple copy of an existing ifs.anon one?) and when trying to vote or comment even though SP is slow and reported as having published to 2 peers, it DOES NOT update anything on the Cluster, so the proxies do not pick it up.

**Comment by dnelband** [comment]
ok ive been able to reproduce this issue and solve it on another peer:
- the problem is not with the certificate, but with the old user that was created with the previous certificate function that didn't work. so now, that user identity has a folder on the zv cluter with a content.json that contains old / previous hash values, and the new certificate doesnt fix that
- there are two solutions:
a - delete the content.json file & SP with user 
b - create the zv.certificate on the zerovoat test zite - its the same certificate but it will use the unique identity of your user on the test zite, thus creating a new certificate with a new identity hash, which will enable you to create & publish content on the zerovoat main site.

this problem will not repeat itself with new users
