### ISSUE TITLE
Post view: indicate there is content to load

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#91]
its just an empty space, that should be at top of post and indicate there should be an img or video:/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/index.html?v=topic+id=1Cma1m5GPL8Dyjg7U5xm5CJUyBbUdZYNSytopic1

![snap 2018-02-05 at 18 37 19](https://user-images.githubusercontent.com/20817185/35819688-c0f7bc48-0aa3-11e8-9a1f-08fb2497873e.png)

**Comment by dnelband** [comment]
that post specifically had an embed url that show nothing (just the address of the zite) . i've fixed it so that it will show a 404 not found image error on such cases of invalid embed links.

since the update i've added a validation for the topic form to allow embeded links that start with merged-CDN only (no clearnet / non merged sites links), i'll improve this validation to force any link to fit the intire correct pattern.

videos & images on topic view have a loading overlay + a question mark dummy image to be displayed while image is being loaded / read.
